### ISSUE TITLE
Compass just spins on 1.15.2

### ISSUE THREAD

**Issue by tobi-polar** [Tfarcenim/EnderCompass#2] opened 2020-04-05 02:21 UTC
Used /locate stronghold to find a stronghold, flew around it a bit, compass wasnt pointing to it at all..

**Comment by SapleMyrup** [comment] 2020-04-19 15:59
> Used /locate stronghold to find a stronghold, flew around it a bit, compass wasnt pointing to it at all..

same thing on 1.15.2.

**Comment by Tfarcenim** [comment] 2020-07-15 02:48
dupe of #4

**Closed as completed by Tfarcenim** 2020-07-15 02:48 UTC
